jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node: [6, 8, 10]
    steps:
      - use: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          